### ISSUE TITLE
GitPropertyController中的saveProperties(...)方法每次执行git clone命令时会报错

### ISSUE THREAD

**Issue by liangweilu** [dyc87112/spring-cloud-config-admin#116]
从界面上点击:`配置中心获取`，或者是`保存配置`时，会报找不到指定文件的错误。  
1、`配置中心获取`虽然报错，但是确实能获取到。  
2、在保存配置的时候，服务器log显示SUCCESS，但是没有执行`commit`等操作，原因也是因为`git clone `时报错，错误如下：  
```java
java.io.IOException: Cannot run program "git": CreateProcess error=2, 系统找不到指定的文件。
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1048)
	at java.lang.Runtime.exec(Runtime.java:620)
	at java.lang.Runtime.exec(Runtime.java:450)
	at com.didispace.easyutils.cmd.CmdRunner.execute(CmdRunner.java:50)
	at com.didispace.easyutils.cmd.CmdRunner.execute(CmdRunner.java:25)
	at com.didispace.scca.plugin.git.GitPropertyController.saveProperties(GitPropertyController.java:115)
```

**Comment by byeluliangwei** [comment]
如果是因为找不到git的安装路径造成的，请问提供了配置git安装路径的参数吗

**Comment by yearyeardiff** [comment]
检查机器是否安装git
